// <auto-generated />
using System;
using Infrastructure.FarmRegistry.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Registration.Migrations
{
    [DbContext(typeof(RegistrationContext))]
    [Migration("20240111225022_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SharedDomain.Entities.Subscribe.FarmRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(5000)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Content")
                        .HasMaxLength(5000)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("IsApprove")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModify")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PaymentDetail")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("SiteKey")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<Guid>("SolutionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SolutionId");

                    b.ToTable("FarmRegistrations");
                });

            modelBuilder.Entity("SharedDomain.Entities.Subscribe.PackageSolution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("varchar(150)");

                    b.Property<long?>("DurationHour")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModify")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("PackageSolutions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e89cf903-ef59-4098-a0aa-17869be91538"),
                            CreatedDate = new DateTime(2024, 1, 12, 5, 50, 22, 591, DateTimeKind.Local).AddTicks(5420),
                            Description = "This is cheapest solution",
                            DurationHour = 750L,
                            IsDeleted = false,
                            LastModify = new DateTime(2024, 1, 12, 5, 50, 22, 591, DateTimeKind.Local).AddTicks(5429),
                            Name = "Solution 1",
                            Price = 10m
                        },
                        new
                        {
                            Id = new Guid("c5e6a8eb-ac87-453d-a8e5-098cd119ec04"),
                            CreatedDate = new DateTime(2024, 1, 12, 5, 50, 22, 591, DateTimeKind.Local).AddTicks(5505),
                            Description = "This is medium solution",
                            DurationHour = 7800L,
                            IsDeleted = false,
                            LastModify = new DateTime(2024, 1, 12, 5, 50, 22, 591, DateTimeKind.Local).AddTicks(5506),
                            Name = "Solution 2",
                            Price = 100m
                        },
                        new
                        {
                            Id = new Guid("2feec9a3-1685-4220-80f3-435dcce6a99a"),
                            CreatedDate = new DateTime(2024, 1, 12, 5, 50, 22, 591, DateTimeKind.Local).AddTicks(5508),
                            Description = "This is vip solution",
                            DurationHour = 79000L,
                            IsDeleted = false,
                            LastModify = new DateTime(2024, 1, 12, 5, 50, 22, 591, DateTimeKind.Local).AddTicks(5509),
                            Name = "Solution 3",
                            Price = 1000m
                        });
                });

            modelBuilder.Entity("SharedDomain.Entities.Subscribe.FarmRegistration", b =>
                {
                    b.HasOne("SharedDomain.Entities.Subscribe.PackageSolution", "Solution")
                        .WithMany()
                        .HasForeignKey("SolutionId")
                        .IsRequired();

                    b.Navigation("Solution");
                });
#pragma warning restore 612, 618
        }
    }
}
