version: "3.4"

services:

    sqldb:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        container_name: 'Sql'
        ports:
          - "1440:1433"
        networks:
          learn.network:
            ipv4_address: 10.38.0.11
        environment:
          - MSSQL_SA_PASSWORD=@El123456
          - ACCEPT_EULA=Y
          - MSSQL_PID=Developer

        volumes: 
          - ./sqldb/data:/var/opt/mssql/data
          - ./sqldb/log:/var/opt/mssql/log
          - ./sqldb/secrets:/var/opt/mssql/secrets

    gateway:
        build:
          context: .
          dockerfile: src/Backend/Gateways/API.Gateway/Dockerfile
        networks:
          learn.network:
            ipv4_address: 10.38.0.10
        ports:
          - "1111:80"
        depends_on:
          - sqldb

    

    authentication:
        container_name: 'AuthS'
        build:
          context: .
          dockerfile: src/Backend/Services/Service.Authentication/Dockerfile
        networks:
          learn.network:
            ipv4_address: 10.38.0.6
        ports:
          - "2222:80"
        depends_on:
          - sqldb
    
    learning:
        build:
          context: .
          dockerfile: src/Backend/Services/Service.Learning/Dockerfile
        networks:
          learn.network:
            ipv4_address: 10.38.0.2
        ports:
          - "3333:80"
        depends_on:
          - sqldb
    
    payment:
        build:
          context: .
          dockerfile: src/Backend/Services/Service.Payment/Dockerfile
        networks:
          learn.network:
            ipv4_address: 10.38.0.3
        ports:
          - "4444:80"
        depends_on:
          - sqldb
    
    procedure:
        build:
          context: .
          dockerfile: src/Backend/Services/Service.Procedure/Dockerfile
        networks:
          learn.network:
            ipv4_address: 10.38.0.4
        ports:
          - "5555:80"
        depends_on:
          - sqldb
    
    social:
        build:
          context: .
          dockerfile: src/Backend/Services/Service.Social/Dockerfile
        networks:
          learn.network:
            ipv4_address: 10.38.0.5
        ports:
          - "6666:80"
        depends_on:
          - sqldb

networks:
  learn.network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.38.0.0/24
