version: "3.4"

services:

    sqldb:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        container_name: 'Agri-Sql'
        ports:
          - "1440:1433"
        networks:
          agri.network:
            ipv4_address: 10.38.0.11
        environment:
          - MSSQL_SA_PASSWORD=@o123456
          - ACCEPT_EULA=Y
          - MSSQL_PID=Developer

        volumes: 
          - ./sqldb/data:/var/opt/mssql/data
          - ./sqldb/log:/var/opt/mssql/log
          - ./sqldb/secrets:/var/opt/mssql/secrets
 
    rabbitmq:
        image: rabbitmq:3-management
        container_name: 'Farm-RBMsgBus'
        ports:
            - 5672:5672
            - 15672:15672
        
        networks:
            agri.network:
                ipv4_address: 10.38.0.12
        environment:
            - RABBITMQ_DEFAULT_USER=farmer
            - RABBITMQ_DEFAULT_PASS=farmer

    service.register:
        build:
          context: .
          dockerfile: src/Services/Service.FarmRegistration/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Staging
            - ASPNETCORE_URLS=http://+:80
        networks:
          agri.network:
            ipv4_address: 10.38.0.3
        ports:
         - "80:80"
        depends_on:
          - sqldb

networks:
  agri.network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.38.0.0/24
