version: "3.8"

services:

    Nsqldb:
        image: postgres:latest
        container_name: "Npgsql_Db"
        ports:
          - '5432:5432'
        restart: always
        networks:
          agri.network:
            ipv4_address: 10.38.0.13
        environment:
          - POSTGRES_USER=farmer
          - POSTGRES_PASSWORD=@o123456
        

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        environment:
          - PGADMIN_DEFAULT_EMAIL=admin@system.vn
          - PGADMIN_DEFAULT_PASSWORD=admin1234
        restart: always
        ports:
          - '5050:80'
        networks:
          agri.network:
            ipv4_address: 10.38.0.14


    service.registration:
        environment:
            - ASPNETCORE_ENVIRONMENT=Testing
            - ASPNETCORE_URLS=http://+:80
          
    service.farmsite:
        environment:
            - ASPNETCORE_ENVIRONMENT=Testing
            - ASPNETCORE_URLS=http://+:80
    
    service.identity:
        environment:
            - ASPNETCORE_ENVIRONMENT=Testing
            - ASPNETCORE_URLS=http://+:80
    
    service.soil:
        environment:
            - ASPNETCORE_ENVIRONMENT=Testing
            - ASPNETCORE_URLS=http://+:80

    service.seed:
        environment:
            - ASPNETCORE_ENVIRONMENT=Testing
            - ASPNETCORE_URLS=http://+:80

    service.pesticide:
        environment:
            - ASPNETCORE_ENVIRONMENT=Testing
            - ASPNETCORE_URLS=http://+:80

    service.fertilize:
        environment:
            - ASPNETCORE_ENVIRONMENT=Testing
            - ASPNETCORE_URLS=http://+:80

    service.equipment:
        environment:
            - ASPNETCORE_ENVIRONMENT=Testing
            - ASPNETCORE_URLS=http://+:80

    service.water:
        environment:
            - ASPNETCORE_ENVIRONMENT=Testing
            - ASPNETCORE_URLS=http://+:80

    service.cultivation:
        environment:
            - ASPNETCORE_ENVIRONMENT=Testing
            - ASPNETCORE_URLS=http://+:80 

    service.supplycontract:
        environment:
            - ASPNETCORE_ENVIRONMENT=Testing
            - ASPNETCORE_URLS=http://+:80

    service.disease:
        environment:
            - ASPNETCORE_ENVIRONMENT=Testing
            - ASPNETCORE_URLS=http://+:80

    service.riskassessment:
        environment:
            - ASPNETCORE_ENVIRONMENT=Testing
            - ASPNETCORE_URLS=http://+:80

    service.globalgap:
        environment:
            - ASPNETCORE_ENVIRONMENT=Testing
            - ASPNETCORE_URLS=http://+:80

    service.payment:
        environment:
            - ASPNETCORE_ENVIRONMENT=Testing
            - ASPNETCORE_URLS=http://+:80

    service.training:
        environment:
            - ASPNETCORE_ENVIRONMENT=Testing
            - ASPNETCORE_URLS=http://+:80