version: "3.8"

services:

    rabbitmq:
        image: rabbitmq:3-management
        container_name: 'Farm-RBMsgBus'
        ports:
            - 5672:5672
            - 15672:15672
        
        networks:
            agri.network:
                ipv4_address: 10.38.0.12
        environment:
            - RABBITMQ_DEFAULT_USER=farmer
            - RABBITMQ_DEFAULT_PASS=farmer

    gateway.ocelot:
        build:
          context: .
          dockerfile: src/Gateways/OcelotGateway/Dockerfile
        ports:
          - '80:80'
        environment:
            - ASPNETCORE_ENVIRONMENT=Staging
            - ASPNETCORE_URLS=http://+:80
        networks:
          agri.network:
            ipv4_address: 10.38.0.2

    service.registration:
        build:
          context: .
          dockerfile: src/Services/Service.FarmRegistration/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Staging
            - ASPNETCORE_URLS=http://+:80
        networks:
          agri.network:
            ipv4_address: 10.38.0.3
        

          
    service.farmsite:
        build:
          context: .
          dockerfile: src/Services/Service.FarmSite/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Staging
            - ASPNETCORE_URLS=http://+:80
        networks:
          agri.network:
            ipv4_address: 10.38.0.4
        

          
    service.identity:
        build:
          context: .
          dockerfile: src/Services/Service.Identity/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Staging
            - ASPNETCORE_URLS=http://+:80
        networks:
          agri.network:
            ipv4_address: 10.38.0.5
     

    service.riskassessment:
        build:
          context: .
          dockerfile: src/Services/Service.RiskAssessment/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Staging
            - ASPNETCORE_URLS=http://+:80
        networks:
          agri.network:
            ipv4_address: 10.38.0.6

    service.soil:
        build:
          context: .
          dockerfile: src/Services/Service.FarmSoil/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Staging
            - ASPNETCORE_URLS=http://+:80
        networks:
          agri.network:
            ipv4_address: 10.38.0.7

    service.seed:
        build:
          context: .
          dockerfile: src/Services/Service.Seed/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Staging
            - ASPNETCORE_URLS=http://+:80
        networks:
          agri.network:
            ipv4_address: 10.38.0.8

    
    service.pesticide:
        build:
          context: .
          dockerfile: src/Services/Service.FarmPesticide/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Staging
            - ASPNETCORE_URLS=http://+:80
        networks:
          agri.network:
            ipv4_address: 10.38.0.9

    service.fertilize:
        build:
          context: .
          dockerfile: src/Services/Service.FarmFertilize/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Staging
            - ASPNETCORE_URLS=http://+:80
        networks:
          agri.network:
            ipv4_address: 10.38.0.10

    service.equipment:
        build:
          context: .
          dockerfile: src/Services/Service.Equipment/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Staging
            - ASPNETCORE_URLS=http://+:80
        networks:
          agri.network:
            ipv4_address: 10.38.0.11

    service.water:
        build:
          context: .
          dockerfile: src/Services/Service.FarmWater/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Staging
            - ASPNETCORE_URLS=http://+:80
        networks:
          agri.network:
            ipv4_address: 10.38.0.15

    service.cultivation:
        build:
          context: .
          dockerfile: src/Services/Service.FarmCultivation/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Staging
            - ASPNETCORE_URLS=http://+:80
        networks:
          agri.network:
            ipv4_address: 10.38.0.16
            
    service.supplycontract:
        build:
          context: .
          dockerfile: src/Services/Service.Supply/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Staging
            - ASPNETCORE_URLS=http://+:80
        networks:
          agri.network:
            ipv4_address: 10.38.0.17
    
    service.disease:
        build:
          context: .
          dockerfile: src/Services/Service.Disease/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Staging
            - ASPNETCORE_URLS=http://+:80
        networks:
          agri.network:
            ipv4_address: 10.38.0.18


networks:
  agri.network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.38.0.0/24
