// <auto-generated />
using System;
using Infrastructure.Disease.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Disease.Migrations
{
    [DbContext(typeof(DiseaseContext))]
    partial class DiseaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SharedDomain.Entities.Diagnosis.DiseaseDiagnosis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Feedback")
                        .HasColumnType("varchar(150)");

                    b.Property<int>("FeedbackStatus")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LandId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModify")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Location")
                        .HasColumnType("varchar(150)");

                    b.Property<Guid>("PlantDiseaseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlantDiseaseId");

                    b.ToTable("DiseaseDiagnoses");
                });

            modelBuilder.Entity("SharedDomain.Entities.Diagnosis.DiseaseInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("varchar(150)");

                    b.Property<Guid?>("CreateBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DiseaseName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModify")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PreventiveMeasures")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Suggest")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("varchar(150)");

                    b.Property<Guid?>("UpdateBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("DiseaseInfos");
                });

            modelBuilder.Entity("SharedDomain.Entities.Diagnosis.DiseaseDiagnosis", b =>
                {
                    b.HasOne("SharedDomain.Entities.Diagnosis.DiseaseInfo", "PlantDisease")
                        .WithMany()
                        .HasForeignKey("PlantDiseaseId")
                        .IsRequired();

                    b.Navigation("PlantDisease");
                });
#pragma warning restore 612, 618
        }
    }
}
